const subReddits = [
  "360 Video",
  "Accidental Comedy",
  "Am I Being Detained",
  "Artisan Videos",
  "Awful Commercials",
  "Best Of Liveleak",
  "Commercial Cuts",
  "Contagious Laughter",
  "Cooking Videos",
  "Cringe",
  "Curious Videos",
  "Deep Into YouTube",
  "Documentaries",
  "Educative Videos",
  "Fast Workers",
  "Fight Porn",
  "Fucking With Nature",
  "Full Movies On YouTube",
  "Full TV Shows On You Tube",
  "Happy Crowds",
  "IMGXXXX",
  "Idiots Fighting Things",
  "Lectures",
  "Listen To This",
  "Livestream Fail",
  "Meal Time Videos",
  "Motivation Videos",
  "Obscure Media",
  "Play It Again Sam",
  "Premature Celebration",
  "Public Freakout",
  "RoadCam",
  "Street Fights",
  "Sweet Justice",
  "Ted",
  "The Way We Were On Video",
  "Trailers",
  "Unexpected Thug Life",
  "Useful Vids",
  "Video Porn",
  "Videos",
  "Vids",
  "Vines",
  "Virtual Freakout",
  "WoahTube",
  "Youtube Haiku"
]

export default subReddits